/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAgenteRouteImport } from './routes/super-agente'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CardMagicoRouteImport } from './routes/card-magico'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SuperAgenteRoute = SuperAgenteRouteImport.update({
  id: '/super-agente',
  path: '/super-agente',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CardMagicoRoute = CardMagicoRouteImport.update({
  id: '/card-magico',
  path: '/card-magico',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agente': typeof AgenteRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/card-magico': typeof CardMagicoRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/radar': typeof RadarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/super-agente': typeof SuperAgenteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agente': typeof AgenteRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/card-magico': typeof CardMagicoRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/radar': typeof RadarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/super-agente': typeof SuperAgenteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/agente': typeof AgenteRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/card-magico': typeof CardMagicoRoute
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/precos': typeof PrecosRoute
  '/radar': typeof RadarRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/super-agente': typeof SuperAgenteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agente'
    | '/biblioteca'
    | '/cadastro'
    | '/card-magico'
    | '/dashboard'
    | '/editor'
    | '/esqueci-senha'
    | '/login'
    | '/precos'
    | '/radar'
    | '/redefinir-senha'
    | '/super-agente'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/agente'
    | '/biblioteca'
    | '/cadastro'
    | '/card-magico'
    | '/dashboard'
    | '/editor'
    | '/esqueci-senha'
    | '/login'
    | '/precos'
    | '/radar'
    | '/redefinir-senha'
    | '/super-agente'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agente'
    | '/biblioteca'
    | '/cadastro'
    | '/card-magico'
    | '/dashboard'
    | '/editor'
    | '/esqueci-senha'
    | '/login'
    | '/precos'
    | '/radar'
    | '/redefinir-senha'
    | '/super-agente'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AgenteRoute: typeof AgenteRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CadastroRoute: typeof CadastroRoute
  CardMagicoRoute: typeof CardMagicoRoute
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  PrecosRoute: typeof PrecosRoute
  RadarRoute: typeof RadarRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SuperAgenteRoute: typeof SuperAgenteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-agente': {
      id: '/super-agente'
      path: '/super-agente'
      fullPath: '/super-agente'
      preLoaderRoute: typeof SuperAgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card-magico': {
      id: '/card-magico'
      path: '/card-magico'
      fullPath: '/card-magico'
      preLoaderRoute: typeof CardMagicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AgenteRoute: AgenteRoute,
  BibliotecaRoute: BibliotecaRoute,
  CadastroRoute: CadastroRoute,
  CardMagicoRoute: CardMagicoRoute,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  PrecosRoute: PrecosRoute,
  RadarRoute: RadarRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SuperAgenteRoute: SuperAgenteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
